[package]
name = "backblaze-b2-client"
version = "0.2.0"
edition = "2021"
rust-version = "1.88"
license = "MIT"
description = "Backblaze B2 Client for Rust"
repository = "https://github.com/SalahaldinBilal/backblaze-b2-client-rs"
readme = "README.md"
keywords = ["backblaze", "b2", "api", "client"]
categories = ["api-bindings"]
exclude = [".vscode"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.23.1"
reqwest = { version = "0.13.5", features = ["json", "stream", "query"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.2", features = ["full"] }
strum_macros = "0.28.0"
typed-builder = "0.23.2"
serde_json = "1.0.151"
serde_with = "3.24.0"
num = "0.4.3"
futures-core = "0.3.34"
bytes = "1.12.1"
futures = "0.3.34"
sha1_smol = { version = "1.0.1", features = ["std"] }
async-stream = "0.3.6"
rand = "0.10.3"
percent-encoding = "2.3.2"

[workspace]
resolver = "2"
